### ISSUE TITLE
Original issue still present in output slot of most GUIs

### ISSUE THREAD

**Issue by Foozey** [SiverDX/obscure_tooltips_fix#2]
Hey there, great fix, thank you. The issue still exists in the item output slot of most GUIs, vanilla or modded. Here are screenshots from the Anvil (Vanilla) and the Reforging Table (Apotheosis):

![image](https://github.com/user-attachments/assets/7a37ad9c-39a0-4ce0-95dd-ad918e50f139)
![image](https://github.com/user-attachments/assets/af0e61b5-8e02-421e-b002-f4cd3c0f4fb2)

**Comment by SiverDX** [comment]
![image](https://github.com/user-attachments/assets/385477b5-ad04-4880-98ad-976e5fa25e3d)

it doesn't with just emi / jei

**Comment by Foozey** [comment]
Must be something else clashing, I'll investigate further

**Comment by Foozey** [comment]
Are you sure you tested it with Apotheosis? For me, this issue is definitely linked to Apotheosis:

With only Obscure Tooltips + Fix installed it's fine:
![image](https://github.com/user-attachments/assets/e857e1f0-cb5c-40b3-8356-1949dcb923c2)
![image](https://github.com/user-attachments/assets/3a70dacd-4ce1-42f0-ac68-378ca44647cd)

With Apotheosis installed it's bugged:
![image](https://github.com/user-attachments/assets/d74b9d85-ee35-4afd-b740-b7e4fc6971dd)
![image](https://github.com/user-attachments/assets/9944d0ac-6883-40cd-b570-1127a8be6c2d)

**Comment by SiverDX** [comment]
![image](https://github.com/user-attachments/assets/b720e88b-b9dc-42e9-be20-f7c55bcc6147)

The primary focus of this mod is to fix an incomaptibility between EMI and Obscure Tooltips
It works when EMI is present but it's bugged with JEI (and no changes are made if neither are present)
