### ISSUE TITLE
Bug with FTBQuests

### ISSUE THREAD

**Issue by TysonTheEmber** [SiverDX/obscure_tooltips_fix#3]
Hovering over a quest item seems to be a little broken...
![image](https://github.com/user-attachments/assets/03d5cdce-6b9e-4d28-9d36-cc54b5c6a944)

**Comment by SiverDX** [comment]
Not sure what your setup is

FTB Quest: No icon
FTB Quest + EMI: No icon
FTB Quest + JEI: No icon
FTB Quest + EMI + JEI: Correct icon

![image](https://github.com/user-attachments/assets/5b8f5544-298a-4da8-8f7f-adcc5f26e159)

![image](https://github.com/user-attachments/assets/4f63f67f-56c6-4774-807b-07d03366dad5)

**Comment by TysonTheEmber** [comment]
FTBQuests + EMI + ObscureTooltips Fix + JEI

**Comment by TysonTheEmber** [comment]
It seems to only happen when using a image as the icon and not an item...

**Comment by TysonTheEmber** [comment]
this is when I changed it from the mod image to the item asset
![image](https://github.com/user-attachments/assets/5e2c810d-4163-42ec-96f0-37105f6518bb)
To explain. You can left click to change the icon to a item, or right click to change it to an image(from the mods source files/textures folder)

**Comment by TysonTheEmber** [comment]
Like what is this... I just put it as the image bc the item isn't registered...
![image](https://github.com/user-attachments/assets/031f2253-c775-4942-a1bc-af0cfbec6f48)
